---

version: '3.8'
services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myapppass
    volumes:
    - db-data:/var/lib/mysql
  web:
    build: 
      dockerfile: Dockerfile.web
    depends_on:
    - db
    environment:
      DSN: 'mysql:host=db;dbname=myapp;charset=utf8mb4'
      DB_USER: myappuser
      DB_PASS: myapppass
      PORT: 8000
    ports:
    - 8563:8000
    volumes:
    - ./work:/work

volumes:
  db-data: